### ISSUE TITLE
Visual bug with field on AetherSX2

### ISSUE THREAD

**Issue by curlyface** [ncaanext/ncaa06-next#61]
Emulator used: AetherSX2 on Android (both versions from the compatible emulators list at https://emulators.ncaanext.com/)

Issue: The field lines appear to be low quality when using AetherSX2 on Android for most if not all stadiums. The yard numbers and 25-yard logo seem to show up fine though. Additionally, when creating a school with a midfield logo, the midfield logo seems to disappear in game.

Additional Information: Files installed using IMGBURN. This issue seems to only be present in 14+ versions of the mod.

**Comment by antdroidx** [comment]
https://www.ncaanext.com/p/next-24-created-teams-guide.html
